name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: '1.12.3.1577'

    - uses: actions/cache@v4.3.0
      with:
        path: ~/.m2
        key: default-build

    - run: clojure -T:build ci

    - uses: codecov/codecov-action@v5.5.1

    - name: deploy
      if: github.event.release
      run: clojure -T:build deploy
      env:
        CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
        CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
